clc;
name='指数分布';
N=50;
lamda=5;
Xi=exprnd(lamda,1,1000);
mXi=mean(Xi)
varXi=var(Xi)
subplot(4,1,1);hist(Xi),title(strcat(name,'直方图'));
X=0:N;
Y_pdf=exppdf(X,lamda);
subplot(4,1,2);plot(X,Y_pdf),title(strcat(name,'概率密度函数'));
Y_cdf=expcdf(X,lamda);
subplot(4,1,3);plot(X,Y_cdf),title(strcat(name,'概率分布函数'));
[m,v]=expstat(lamda)
[Rx,lags]=xcorr(Xi);
subplot(4,1,4);plot(lags/1,Rx),title(strcat(name,'信号自相关函数'));