M=500;
Ts=0.001;
B=0.5*1/Ts;
t=0:Ts:(M-1)*Ts;
F=0:1:B;%仿真频率范围
f=200;%信号频率
A=4;%幅度
S_t=4*sin(2*pi*f.*t);%sin 信号
mu=0;
N0=0.001;%噪声功率谱密度
sigma=sqrt(N0*B);
N_t=normrnd(mu,sigma,1,M);
X_t=S_t+N_t;

f_cutoff=220;
LPF=[ones(1,f_cutoff),zeros(1,B+1-f_cutoff)];
BPF=[zeros(1,200),ones(1,10),zeros(1,B+1-200-10)];
F_1=2.*F.*Ts;
[b_LPF,a_LPF]=yulewalk(10,F_1,LPF);
[b_BPF,a_BPF]=yulewalk(10,F_1,BPF);
Y_LPF_t=filter(b_LPF,a_LPF,X_t);
Y_BPF_t=filter(b_BPF,a_BPF,X_t);
figure(1);
subplot(2,2,1),plot(t,X_t),title('带白噪声信号时域波形');
subplot(2,2,2);periodogram(X_t,[],M,1/Ts);
subplot(2,2,3);plot(t,Y_LPF_t),title('带白噪声信号通过低通系统后时域波形');
subplot(2,2,4);periodogram(Y_LPF_t,[],M,1/Ts);
figure(2);
subplot(2,2,1),plot(t,X_t),title('带白噪声信号时域波形');
subplot(2,2,2);periodogram(X_t,[],M,1/Ts);
subplot(2,2,3);plot(t,Y_BPF_t),title('带白噪声信号通过带通系统后时域波形');
subplot(2,2,4);periodogram(Y_BPF_t,[],M,1/Ts);